spring.devtools.restart.enabled=false
spring.application.name=inventario

# Firebase — JSON en disco (inventario/auth/), fuera de target
firebase.config.path=auth/serviceAccountKey.json
firebase.collection.computadoras=computadoras
firebase.collection.camaras=camaras
